# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rui Albuquerque
tagline:          #The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

  modified by:    Rui Albuquerque
  based on:       joshualande.com / github.com/joshualande/joshualande.github.io
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

#added by me
# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Projects':'/projects','Archive':'/archive','Feed':'/atom.xml'}


projects_list:    {'CipherChat':'https://github.com/rui278/CipherChat'}
projects_text:    {'CipherChat':'here'}
  
  
links_list:       {'twitter':'stuff','gitHub':'github'}
