# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rui Albuquerque
tagline:          #The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

  modified by:    Rui Albuquerque
  based on:       joshualande.com / github.com/joshualande/joshualande.github.io
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

#added by me
# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about',
                   'Projects':'/projects','Archive':'/archive',
                   'Twitter':'https://twitter.com/rui278','GitHub':'https://github.com/rui278',
                   'Feed':'/atom.xml'
                   }



projects_list:    {'CipherChat':'https://github.com/rui278/CipherChat',
                   'CipherManager':'https://github.com/rui278/CipherManager',
                   'Cuda Kmeans':'https://github.com/rui278/cudaKmeans',
                   'Dinamic Directories':'https://github.com/rui278/Dinamic-Directories'}
                   
projects_text:    {'CipherChat':'An Android chat app that provides secure and confidential conversations among users. It uses the Revised Needham-Shroeder Protocol to provide confidentiality, authentication, freshness and integrity. It purposely does not assure non-repudiation so that full client privacy can be respected.',
                   'CipherManager':'A simple desktop password manager. You can use, view or create passwords. Passwords are stored localy. uses AES and SHA256.',
                   'Cuda Kmeans':'A Kmeans Implementation using Cuda to enable GPU usage and acceleration.',
                   'Dinamic Directories':'A dinamic user directory based chat application'
                   }
  
