var annotated =
[
    [ "ppa", "namespaceppa.html", "namespaceppa" ],
    [ "x265", "namespacex265.html", "namespacex265" ],
    [ "CLIOptions", "structCLIOptions.html", "structCLIOptions" ],
    [ "CUData", "structCUData.html", "structCUData" ],
    [ "DctConf", "structDctConf.html", "structDctConf" ],
    [ "IntraPredHarness", "classIntraPredHarness.html", "classIntraPredHarness" ],
    [ "IPFilterHarness", "classIPFilterHarness.html", "classIPFilterHarness" ],
    [ "MBDstHarness", "classMBDstHarness.html", "classMBDstHarness" ],
    [ "MD5Frame", "classMD5Frame.html", "classMD5Frame" ],
    [ "option", "structoption.html", "structoption" ],
    [ "PixelHarness", "classPixelHarness.html", "classPixelHarness" ],
    [ "RowData", "structRowData.html", "structRowData" ],
    [ "TestHarness", "classTestHarness.html", "classTestHarness" ],
    [ "x265_analysis_data", "structx265__analysis__data.html", "structx265__analysis__data" ],
    [ "x265_cli_csp", "structx265__cli__csp.html", "structx265__cli__csp" ],
    [ "x265_encoder", "structx265__encoder.html", null ],
    [ "x265_inter_data", "structx265__inter__data.html", "structx265__inter__data" ],
    [ "x265_intra_data", "structx265__intra__data.html", "structx265__intra__data" ],
    [ "x265_nal", "structx265__nal.html", "structx265__nal" ],
    [ "x265_param", "structx265__param.html", "structx265__param" ],
    [ "x265_picture", "structx265__picture.html", "structx265__picture" ],
    [ "x265_stats", "structx265__stats.html", "structx265__stats" ]
];